version: "3"
services: 
  web:
    command: npm run start
    container_name: wine-backend
    build: './backend'
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always