version: "3.3"

services:
  backend:
    container_name: wine-backend
    build:
      context: ./backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"

  server:
    container_name: wine-client
    build:
      context: ./client
    ports:
      - '8080:8080'
